package pacotes;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.Timer;
import javax.swing.filechooser.FileNameExtensionFilter;

public final class TelaUsuario extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form TelaUsuario
     */
    public TelaUsuario() {
        initComponents();
        // grupo1();
        update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jAbrir = new javax.swing.JFileChooser();
        jSalvar = new javax.swing.JFileChooser();
        jPanel4 = new javax.swing.JPanel();
        painelLocal = new javax.swing.JPanel();

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        varDOIS = new javax.swing.JTextField();
        try{    DecimalFormat z = new DecimalFormat("0.##");  z.format(varDOIS);            }catch(Exception e){   }
        varTRES = new javax.swing.JTextField();
        try{

            DecimalFormat z = new DecimalFormat("0.##");
            z.format(varTRES);

        }catch(Exception e){
        }

        btLocal = new javax.swing.JButton();
        painelGeral = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        varUM = new javax.swing.JTextField();
        try{    DecimalFormat z = new DecimalFormat("0.##");  z.format(varUM);            }catch(Exception e){   }
        btGeral = new javax.swing.JButton();
        painelDados = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        informa = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btSalvar = new javax.swing.JLabel();
        try{  btSalvar.setVisible(false);  }catch(Exception e){    }
        jLabel34 = new javax.swing.JLabel();

        btAbrir = new javax.swing.JButton();
        painelTela = new javax.swing.JPanel();
        textoTela = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        corLegenda = new javax.swing.JLabel();
        try{
            corLegenda.setVisible(false);
        }catch(Exception e){

        }
        cd1 = new javax.swing.JLabel();
        cd2 = new javax.swing.JLabel();
        cd3 = new javax.swing.JLabel();
        cd4 = new javax.swing.JLabel();
        cd5 = new javax.swing.JLabel();
        cd6 = new javax.swing.JLabel();

        jAbrir.setAcceptAllFileFilterUsed(false);

        jSalvar.setAcceptAllFileFilterUsed(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(923, 667));
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(913, 661));
        jPanel4.setLayout(null);

        painelLocal.setBackground(new java.awt.Color(255, 255, 255));
        painelLocal.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "LOCAL FILTERING", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bodoni MT", 0, 12), new java.awt.Color(0, 51, 102))); // NOI18N
        painelLocal.setEnabled(false);
        painelLocal.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Variation of limits (%):");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, painelLocal, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), jLabel5, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        painelLocal.add(jLabel5);
        jLabel5.setBounds(10, 57, 138, 17);

        jLabel6.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Spacial dependence (m):");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, painelLocal, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), jLabel6, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        painelLocal.add(jLabel6);
        jLabel6.setBounds(5, 28, 143, 17);

        varDOIS.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        varDOIS.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        varDOIS.setText("10");
        varDOIS.setPreferredSize(new java.awt.Dimension(51, 22));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, painelLocal, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), varDOIS, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        painelLocal.add(varDOIS);
        varDOIS.setBounds(152, 25, 51, 23);

        varTRES.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        varTRES.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        varTRES.setText("25.00");
        varTRES.setPreferredSize(new java.awt.Dimension(51, 22));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, painelLocal, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), varTRES, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        painelLocal.add(varTRES);
        varTRES.setBounds(152, 54, 51, 22);

        btLocal.setBackground(new java.awt.Color(255, 255, 255));
        btLocal.setForeground(new java.awt.Color(255, 255, 255));
        btLocal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacotes/play.png"))); // NOI18N
        btLocal.setBorderPainted(false);
        btLocal.setContentAreaFilled(false);
        btLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLocalActionPerformed(evt);
            }
        });
        painelLocal.add(btLocal);
        btLocal.setBounds(240, 40, 40, 30);

        jPanel4.add(painelLocal);
        painelLocal.setBounds(0, 180, 290, 88);
        painelLocal.getAccessibleContext().setAccessibleParent(painelLocal);

        painelGeral.setBackground(new java.awt.Color(255, 255, 255));
        painelGeral.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "GENERAL FILTERING", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bodoni MT", 0, 12), new java.awt.Color(0, 51, 102))); // NOI18N
        painelGeral.setEnabled(false);
        painelGeral.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Variation of limit (%):");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, painelGeral, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), jLabel3, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        painelGeral.add(jLabel3);
        jLabel3.setBounds(9, 27, 133, 17);

        varUM.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        varUM.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        varUM.setText("100.00");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, painelGeral, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), varUM, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        painelGeral.add(varUM);
        varUM.setBounds(150, 23, 50, 23);

        btGeral.setBackground(new java.awt.Color(255, 255, 255));
        btGeral.setForeground(new java.awt.Color(255, 255, 255));
        btGeral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacotes/play.png"))); // NOI18N
        btGeral.setBorderPainted(false);
        btGeral.setContentAreaFilled(false);
        btGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGeralActionPerformed(evt);
            }
        });
        painelGeral.add(btGeral);
        btGeral.setBounds(240, 20, 40, 30);

        jPanel4.add(painelGeral);
        painelGeral.setBounds(0, 120, 290, 59);

        painelDados.setBackground(new java.awt.Color(255, 255, 255));
        painelDados.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "DATA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bodoni MT", 0, 12), new java.awt.Color(0, 51, 102))); // NOI18N
        painelDados.setPreferredSize(new java.awt.Dimension(290, 290));
        painelDados.setVisible(false);
        painelDados.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Bodoni MT", 0, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("ORIGINAL");
        painelDados.add(jLabel14);
        jLabel14.setBounds(122, 17, 67, 16);

        jLabel15.setFont(new java.awt.Font("Bodoni MT", 0, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("FILTERED");
        painelDados.add(jLabel15);
        jLabel15.setBounds(217, 17, 68, 16);

        jLabel16.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Number of points :");
        painelDados.add(jLabel16);
        jLabel16.setBounds(5, 39, 111, 17);

        jLabel17.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Minimum value    :");
        painelDados.add(jLabel17);
        jLabel17.setBounds(5, 62, 110, 17);

        jLabel18.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Maximum value   :");
        painelDados.add(jLabel18);
        jLabel18.setBounds(5, 85, 109, 17);

        jLabel19.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Average value      :");
        painelDados.add(jLabel19);
        jLabel19.setBounds(5, 108, 107, 17);

        jLabel20.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("Std. deviation       :");
        painelDados.add(jLabel20);
        jLabel20.setBounds(5, 131, 108, 17);

        jLabel21.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("C. V. (%)                :");
        painelDados.add(jLabel21);
        jLabel21.setBounds(5, 154, 107, 17);

        jLabel22.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        painelDados.add(jLabel22);
        jLabel22.setBounds(122, 39, 70, 17);

        jLabel23.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        painelDados.add(jLabel23);
        jLabel23.setBounds(122, 62, 70, 17);

        jLabel24.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        painelDados.add(jLabel24);
        jLabel24.setBounds(122, 85, 70, 17);

        jLabel25.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        painelDados.add(jLabel25);
        jLabel25.setBounds(122, 108, 70, 17);

        jLabel26.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        painelDados.add(jLabel26);
        jLabel26.setBounds(122, 131, 70, 17);

        jLabel27.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        painelDados.add(jLabel27);
        jLabel27.setBounds(122, 154, 70, 17);

        jLabel28.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        painelDados.add(jLabel28);
        jLabel28.setBounds(217, 39, 65, 17);

        jLabel29.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        painelDados.add(jLabel29);
        jLabel29.setBounds(217, 62, 65, 17);

        jLabel30.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        painelDados.add(jLabel30);
        jLabel30.setBounds(217, 85, 65, 17);

        jLabel31.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        painelDados.add(jLabel31);
        jLabel31.setBounds(217, 108, 65, 17);

        jLabel32.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 51, 51));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        painelDados.add(jLabel32);
        jLabel32.setBounds(217, 131, 65, 17);

        jLabel33.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 51, 51));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        painelDados.add(jLabel33);
        jLabel33.setBounds(217, 154, 65, 17);

        informa.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        informa.setForeground(new java.awt.Color(255, 0, 0));
        painelDados.add(informa);
        informa.setBounds(10, 260, 150, 20);

        jPanel4.add(painelDados);
        painelDados.setBounds(0, 380, 290, 287);
        painelDados.getAccessibleContext().setAccessibleParent(painelDados);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "FILE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bodoni MT", 0, 12), new java.awt.Color(0, 51, 102))); // NOI18N
        jPanel1.setLayout(null);

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacotes/disquete32.png"))); // NOI18N
        btSalvar.setAlignmentY(0.4F);
        btSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSalvarMouseClicked(evt);
            }
        });
        jPanel1.add(btSalvar);
        btSalvar.setBounds(250, 10, 30, 40);

        jLabel34.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 102, 102));
        jLabel34.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel34);
        jLabel34.setBounds(50, 30, 100, 17);

        btAbrir.setBackground(new java.awt.Color(255, 255, 255));
        btAbrir.setForeground(new java.awt.Color(255, 255, 255));
        btAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacotes/pasta32.png"))); // NOI18N
        btAbrir.setBorderPainted(false);
        btAbrir.setContentAreaFilled(false);
        btAbrir.setFocusPainted(false);
        btAbrir.setFocusable(false);
        btAbrir.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbrirActionPerformed(evt);
            }
        });
        jPanel1.add(btAbrir);
        btAbrir.setBounds(10, 20, 40, 30);

        jPanel4.add(jPanel1);
        jPanel1.setBounds(0, 60, 290, 56);
        jPanel1.getAccessibleContext().setAccessibleParent(jPanel1);

        painelTela.setBackground(new java.awt.Color(255, 255, 255));
        painelTela.setAutoscrolls(true);
        painelTela.setPreferredSize(new java.awt.Dimension(0, 0));
        painelTela.setLayout(null);

        textoTela.setBackground(new java.awt.Color(255, 255, 255));
        textoTela.setForeground(new java.awt.Color(255, 255, 255));
        textoTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacotes/infoINICIAL.png"))); // NOI18N
        textoTela.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        painelTela.add(textoTela);
        textoTela.setBounds(10, 0, 610, 560);

        jPanel4.add(painelTela);
        painelTela.setBounds(290, 70, 630, 560);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacotes/MAPFILTRO.png"))); // NOI18N
        jPanel4.add(jLabel12);
        jLabel12.setBounds(0, 0, 927, 60);
        jLabel12.getAccessibleContext().setAccessibleParent(jLabel12);

        corLegenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacotes/escala.png"))); // NOI18N
        jPanel4.add(corLegenda);
        corLegenda.setBounds(450, 630, 280, 13);

        cd1.setFont(new java.awt.Font("Bodoni MT", 1, 12)); // NOI18N
        cd1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel4.add(cd1);
        cd1.setBounds(450, 645, 42, 15);

        cd2.setFont(new java.awt.Font("Bodoni MT", 1, 12)); // NOI18N
        cd2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel4.add(cd2);
        cd2.setBounds(493, 645, 42, 15);

        cd3.setFont(new java.awt.Font("Bodoni MT", 1, 12)); // NOI18N
        cd3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(cd3);
        cd3.setBounds(538, 645, 42, 15);

        cd4.setFont(new java.awt.Font("Bodoni MT", 1, 12)); // NOI18N
        cd4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(cd4);
        cd4.setBounds(586, 645, 42, 15);

        cd5.setFont(new java.awt.Font("Bodoni MT", 1, 12)); // NOI18N
        cd5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel4.add(cd5);
        cd5.setBounds(628, 645, 42, 15);

        cd6.setFont(new java.awt.Font("Bodoni MT", 1, 12)); // NOI18N
        cd6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel4.add(cd6);
        cd6.setBounds(672, 645, 42, 15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private final ProcessoGeral process = new ProcessoGeral();
    private File arquivo;
    private final JRadioButton bot1 = new JRadioButton();// cria um novo botão
    private final JRadioButton bot2 = new JRadioButton();// cria um novo botão

    public void botaoabrir() {
        update();
        textoTela.setVisible(false);
        arqfilter(jAbrir);
        int ab;
        ab = jAbrir.showOpenDialog(null);
        if (ab == JFileChooser.APPROVE_OPTION) {
            try {
                arquivo = jAbrir.getSelectedFile();
                process.process1(arquivo);
                jLabel34.setText(jAbrir.getName(arquivo));
                legenda1(process.estat);
                painelGeral.setEnabled(true);
                btGeral.setVisible(true);
                process.telaoriginal(painelTela);
                legenda3(process.mapLeg);
                update2();
                painelGeral.setVisible(true);
                painelDados.setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(TelaUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    public void botaosalvar() {
        arqfilter(jSalvar);
        int janela;
        janela = jSalvar.showSaveDialog(null);
        if (janela == JFileChooser.APPROVE_OPTION) {
            File arquivoSalvar = jSalvar.getSelectedFile();
            String index = jSalvar.getFileFilter().getDescription();
            int ext = 1;
            if ("Text File (*.txt)".equals(index)) {
                ext = 2;
                process.salvardados(2, arquivoSalvar, ext);
            }
            if ("Comma Separated Values (*.csv)".equals(index)) {
                ext = 1;
                process.salvardados(2, arquivoSalvar, ext);
            }
        }
    }

    public void botaofiltrogeral() {
        textoTela.setVisible(false);
        double var = Double.parseDouble(varUM.getText().trim());
        process.filtrogeral(var);
        legenda2(process.estat);
        painelLocal.setEnabled(true);
        btAbrir.setVisible(true);
        btLocal.setVisible(true);
        process.telageral(painelTela);
        legenda3(process.mapLeg);
        update2();
    }

    public void botaofiltrolocal() {
        textoTela.setVisible(false);
        double raio = Double.parseDouble(varDOIS.getText().trim());
        double var = Double.parseDouble(varTRES.getText().trim());
        process.filtrolocal(var, raio);
        legenda2(process.estat);
        process.telalocal(painelTela);
        legenda3(process.mapLeg);
        update2();
        btSalvar.setVisible(true);
    }

    private void btAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbrirActionPerformed
        // TODO add your handling code here:
        informa.setText("Opening file...");
        botaoabrir();
        ActionListener taskPerformer = (ActionEvent evt1) -> {
            informa.setText(" ");
        };
        Timer timer = new Timer(100, taskPerformer); // delay one sec
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_btAbrirActionPerformed

    private void btGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGeralActionPerformed
        // TODO add your handling code here:
        Thread t3 = new Thread(() -> {
            informa.setText("Processing...");
        });
        t3.start();
        Thread t4 = new Thread(() -> {
            botaofiltrogeral();
            informa.setText(" ");
        });
        t4.start();
    }//GEN-LAST:event_btGeralActionPerformed

    private void btLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLocalActionPerformed
        Thread t1 = new Thread(() -> {
            informa.setText("Processing...");
        });
        t1.start();
        Thread t2 = new Thread(() -> {
            botaofiltrolocal();
            informa.setText(" ");
        });
        t2.start();
    }//GEN-LAST:event_btLocalActionPerformed

    private void btSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSalvarMouseClicked
        // TODO add your handling code here:
        botaosalvar();
    }//GEN-LAST:event_btSalvarMouseClicked

    public void arqfilter(JFileChooser x) {
        //filtro de arquivos texto .txt e .csv
        x.resetChoosableFileFilters();
        FileNameExtensionFilter filter;
        filter = new FileNameExtensionFilter("Comma Separated Values (*.csv)",
                "csv");
        x.addChoosableFileFilter(filter);
        filter = new FileNameExtensionFilter("Text File (*.txt)", "txt");
        x.addChoosableFileFilter(filter);
    }

    public void legenda1(double[] stat) {
        //Mostrar estatística pontos originais
        jLabel22.setText(String.format("%.0f", stat[0]));// n pts
        jLabel23.setText(String.format("%.2f", stat[1]));// mínimo
        jLabel24.setText(String.format("%.2f", stat[2]));// máximo
        jLabel25.setText(String.format("%.2f", stat[3]));// média
        jLabel26.setText(String.format("%.2f", stat[4]));// desvio
        jLabel27.setText(String.format("%.2f", stat[5]));// C.V.
    }

    public void legenda2(double[] stat) {
        //Mostrar estátistica pontos filtrados 
        jLabel28.setText(String.format("%.0f", stat[0]));// n pts
        jLabel29.setText(String.format("%.2f", stat[1]));// mínimo
        jLabel30.setText(String.format("%.2f", stat[2]));// máximo
        jLabel31.setText(String.format("%.2f", stat[3]));// média
        jLabel32.setText(String.format("%.2f", stat[4]));// desvio
        jLabel33.setText(String.format("%.2f", stat[5]));// C.V.
    }

    public void legenda3(double[] quartis) {
        corLegenda.setVisible(true);
        cd1.setText(String.format("%.1f", quartis[0]));
        cd2.setText(String.format("%.1f", quartis[1]));
        cd3.setText(String.format("%.1f", quartis[2]));
        cd4.setText(String.format("%.1f", quartis[3]));
        cd5.setText(String.format("%.1f", quartis[4]));
        cd6.setText(String.format("%.1f", quartis[5]));
    }

    public void update() {
        btSalvar.setVisible(false);
        btGeral.setVisible(false);
        btLocal.setVisible(false);
        jLabel28.setText(" ");
        jLabel29.setText(" ");
        jLabel30.setText(" ");
        jLabel31.setText(" ");
        jLabel32.setText(" ");
        jLabel33.setText(" ");
        cd1.setText(" ");
        cd2.setText(" ");
        cd3.setText(" ");
        cd4.setText(" ");
        cd5.setText(" ");
        cd6.setText(" ");
        corLegenda.setVisible(false);
    }

    public void update1() {
        corLegenda.setVisible(false);
        btSalvar.setVisible(false);
        cd1.setVisible(false);
        cd2.setVisible(false);
        cd3.setVisible(false);
        cd4.setVisible(false);
        cd5.setVisible(false);
        cd6.setVisible(false);
    }

    public void update2() {
        corLegenda.setVisible(true);
        // btSalvar.setVisible(true);
        cd1.setVisible(true);
        cd2.setVisible(true);
        cd3.setVisible(true);
        cd4.setVisible(true);
        cd5.setVisible(true);
        cd6.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaUsuario().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbrir;
    private javax.swing.JButton btGeral;
    private javax.swing.JButton btLocal;
    private javax.swing.JLabel btSalvar;
    private javax.swing.JLabel cd1;
    private javax.swing.JLabel cd2;
    private javax.swing.JLabel cd3;
    private javax.swing.JLabel cd4;
    private javax.swing.JLabel cd5;
    private javax.swing.JLabel cd6;
    private javax.swing.JLabel corLegenda;
    private javax.swing.JLabel informa;
    private javax.swing.JFileChooser jAbrir;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JFileChooser jSalvar;
    private javax.swing.JPanel painelDados;
    private javax.swing.JPanel painelGeral;
    private javax.swing.JPanel painelLocal;
    private javax.swing.JPanel painelTela;
    private javax.swing.JLabel textoTela;
    private javax.swing.JTextField varDOIS;
    private javax.swing.JTextField varTRES;
    private javax.swing.JTextField varUM;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
